dataset:
  num_classes: 11
  training:
    video_info_path: STADe-DeepSeg/thumos_annotations/train_BehavePublic_info.csv
    video_anno_path: STADe-DeepSeg/thumos_annotations/train_Behave_Public_annotation.csv
    video_data_path: /root/autodl-tmp/deepseg_Data_npy/
    clip_length: 8000
    clip_stride: 30
    crop_size: 96
  testing:
    video_info_path: STADe-DeepSeg/thumos_annotations/test_BehavePublic_info.csv
    video_anno_path: STADe-DeepSeg/thumos_annotations/test_Behave_Public_annotation.csv
    video_data_path: /root/autodl-tmp/deepseg_Data_npy/
    clip_length: 8000
    clip_stride: 30
    crop_size: 96

model:
  in_channels: 1
  freeze_bn: false
  freeze_bn_affine: false
  backbone_model: STADe-DeepSeg/models/thumos14/checkpoint-15.ckpt
  ConfDim_num: 400  # 将前一个动作的分类结果作为特征是特征的维度设置
  LocDim_num: 100 # 将前一个动作的回归结果作为特征是特征的维度设置
  ConPoolingKernal: [800,20,10,5,3,2,2] # 对锚框中的数据进行卷积池化时卷积核的大小
training:
  batch_size: 2
  learning_rate: 1e-4
  weight_decay: 1e-3
  max_epoch: 60
  focal_loss: true
  checkpoint_path: models/All-Amend_deepseg
  pre_checkpoint_path: models/All-Amend_deepseg
  random_seed: 2020
  model_name: All-Amend_deepseg-lw-6_lc-1
  pre_model_name: All-Amend_deepseg-lw-6_lc-1
  save_model_num: [56,57] # 要保存的指定迭代次次数的模型
testing:
  conf_thresh: 0.01
  top_k: 5000
  nms_thresh: 0.5 # 0.9
  nms_sigma: 0.1 # 0.5
  checkpoint_path: models/All-Amend_deepseg
  output_path: output
  output_json: All-Amend_deepseg-lw-6_lc-1   # 测试结果的文件名
  test_model_name: All-Amend_deepseg-lw-6_lc-1
  